sudo: required
dist: trusty
addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake
language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./install-deps && mkdir build && cd build && cmake .. && make && make test
notifications:
  slack: team-401:onrGUBYH0HkkphR3GEkPjdaT
